# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-04 14:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0003_chambre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chambre',
            name='hotel',
        ),
        migrations.AddField(
            model_name='hotel',
            name='photo',
            field=models.ImageField(null=True, upload_to='photos'),
        ),
        migrations.DeleteModel(
            name='Chambre',
        ),
    ]
